### PR TITLE
initial DCP HAL with AES-128 ECB support

### PR DESCRIPTION
**Pull request by japaric**
the API implements the `BlockCipher` trait and encryption has been tested against the `aesni` crate. 3 key modes are supported:

- (user provided) RAM keys
- OTP key
- UNIQUE key

see the `aes-*` examples and the API docs for more information about the differences of these key modes

Only one instance of the `Aes128` abstraction can be created at the moment but this restriction will be lifted in the future

cc #40

### CODE REVIEW

**Review by tony-iqlusion — APPROVED** [review]

**Comment by tarcieri** [comment]
I think with this change to the `aes-gcm-siv` crate (along with https://github.com/RustCrypto/AEADs/pull/89, and a hypothetical new non-parallel `Ctr` implementation which works for `ParBlocks = U1`) I should be able to instantiate AES-GCM-SIV with this PR (including with the `OTP` or `UNIQUE` keys), but haven't tried yet:

https://github.com/RustCrypto/AEADs/pull/91/files

**Comment by tarcieri** [comment]
Trying to wire everything up in this PR: https://github.com/iqlusioninc/armistice/pull/35

**Comment by tarcieri** [comment]
@japaric so the USB armory Wiki says:

https://github.com/f-secure-foundry/usbarmory/wiki/Hardware-security-features-(Mk-II)

> device specific random 256-bit OTPMK key is fused in each SoC at manufacturing time, this key is unreadable and can only be used by the CAAM (i.MX6UL) or DCP (i.MX6ULZ) for AES encryption/decryption of user data

Is there AES-256(-ECB) support as well?

**Comment by japaric** [comment]
> used by the CAAM (i.MX6UL) or DCP (i.MX6ULZ)

According to the docs (IMX6ULZRM) the DCP (version 0x2010000) only has AES-128 acceleration. The DCP can be configured to use the lower or the higher 128 bits of the 256-bit OTPMK as its "OTP key".

The CAAM can do AES-256 but as the wiki says that module is part of the i.MX6UL chip, which you can get on custom order. I have the retail i.MX6ULZ chip here and it doesn't have a CAAM in it. Except for the `dcp` module added in this PR the rest of the code in the repo should work on either chip.

**Pull request merged**
